### CLASS TASK TWO MATRIX

### Determining (AB)

In [3]:
import numpy as np

A = np.array([[2, -1, 3],
              [0, 4, 1]])

print('A array shape:', A.shape)

B = np.array([[1, 2], [-2, 0],
              [5, -3]])

print('B array shape:', B.shape)

print(A @ B)

A array shape: (2, 3)
B array shape: (3, 2)
[[19 -5]
 [-3 -3]]


### Determining (BA)

In [4]:

B = np.array([[1, 2], [-2, 0],
              [5, -3]])

print('B array shape:', B.shape)


A = np.array([[2, -1, 3],
              [0, 4, 1]])

print('A array shape:', A.shape)

print(B @ A)

B array shape: (3, 2)
A array shape: (2, 3)
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
