In [5]:
import numpy as np
import matplotlib.pyplot as plt
import time

# check Numpy version
print(f"Numpy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)

Numpy version: 2.3.3


In [9]:
# creating arrays from python lists
# 1D array
arr1d = np.array([1, 2, 3, 4, 5])

#2D array: Think of this as a matrix or tabble with rows and columns
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print("1D array:", arr1d)
print("2D array:", arr2d)
print("3D array:", arr3d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]
3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
zeros = np.zeros((4, 4))

ones = np.ones((2, 3, 4))

empty = np.empty((2, 2))

print("Zeros array (3x4):\n", zeros)
print("Ones array shape:", ones.shape)
print("Empty array (contains random value):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random value):
 [[0. 0.]
 [0. 0.]]


In [15]:
range_arr = np.arange(0, 10, 2)
print("Range array:", range_arr)

linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:", linspace_arr)

logspace_arr = np.logspace(0, 2, 5)
print("Logspace array:", logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


In [16]:
identity = np.eye(4)

diagonal = np.diag([1, 2, 3, 4])

full_arr = np.full((3, 3), 7)

print("Identity matrix:", identity)
print("Diagonal matrix:\n", diagonal)
print("Full array (filled with 7):\n", full_arr)



Identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [17]:
# Explicit data types - control memory usage and precision
int_arr = np.array([1, 2, 3], dtype=np.int32)       # 32-bit integers
float_arr = np.array([1, 2, 3], dtype=np.float64)   # 64-bit floats (double precision)
bool_arr = np.array([True, False, True], dtype=np.bool_)  # Boolean values

# Type conversion - change dtype of existing array
converted = int_arr.astype(np.float32)  # Convert to 32-bit float

print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print("Converted array dtype:", converted.dtype)

# Memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element
